### ISSUE TITLE
'str' object has no attribute 'dim'

### ISSUE THREAD

**Issue by shanxiaojun** [ZixuanKe/LifelongSentClass#3]
Thanks for your great work! It seems something is wrong with your source code. I run the script and it turns out like below.
```
Traceback (most recent call last):
  File "run.py", line 134, in <module>
    appr.train(task,train_dataloader,valid_dataloader,args)
  File "/root/autodl-tmp/LifelongSentClass-master/approaches/bert_rnn_kan_ncl.py", line 81, in train
    self.train_epoch(t,train,iter_bar,which_type)
  File "/root/autodl-tmp/LifelongSentClass-master/approaches/bert_rnn_kan_ncl.py", line 126, in train_epoch
    outputs=self.model.forward(task,input_ids, segment_ids, input_mask,which_type,s)
  File "/root/autodl-tmp/LifelongSentClass-master/networks/bert_gru_kan.py", line 45, in forward
    mcl_output,mcl_hidden = self.mcl.gru(sequence_output)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/LifelongSentClass-master/networks/bert_gru_kan.py", line 125, in forward
    output, hidden = self.rnn(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 913, in forward
    is_batched = input.dim() == 3
AttributeError: 'str' object has no attribute 'dim'
```

**Comment by ZixuanKe** [comment]
Hello,

Thank you for your interest in our work. Some packages used in this repository may be outdated. We suggest using PyContinual (https://github.com/ZixuanKe/PyContinual/) instead, which supports KAN. For more information, please refer to the documentation (https://github.com/ZixuanKe/PyContinual/blob/master/docs/baselines.md).

If you have any questions, please do not hesitate to ask us.
Thank you

**Comment by shanxiaojun** [comment]
Thanks for your timely response! I will try your PyContinual instead.
